
int bitNor(int, int);
int test_bitNor(int, int);
int bitMask(int, int);
int test_bitMask(int, int);
int logicalNeg(int);
int test_logicalNeg(int);
int oddBits();
int test_oddBits();
int implication(int, int);
int test_implication(int, int);
int greatestBitPos(int);
int test_greatestBitPos(int);
int isPower2(int);
int test_isPower2(int);
int subOK(int, int);
int test_subOK(int, int);
int isPositive(int);
int test_isPositive(int);
int tmax();
int test_tmax();
int negate(int);
int test_negate(int);
int sign(int);
int test_sign(int);
unsigned float_abs(unsigned);
unsigned test_float_abs(unsigned);
unsigned float_half(unsigned);
unsigned test_float_half(unsigned);
int float_f2i(unsigned);
int test_float_f2i(unsigned);
